Excel parsing ready
tuipik/kan pull request #42
Opened 2024-01-18 15:01 UTC by yourious

2024-01-18 15:38 UTC, didoogan requested changes

2024-01-18 15:38 UTC, didoogan commented on .gitignore
> +/api/management/commands/task_importer/task_updates.xlsx
я б ц файли не додавав сюди

2024-01-18 15:38 UTC, didoogan commented on api/dich_excel.py
> +path = "/home/yurii/PROJECTS/test/Розрахунок виконання робіт_2024.xlsx"
а що це файл? На серваку папки /home/yurii не існує

2024-01-18 15:38 UTC, didoogan commented on api/dich_excel.py
> +import openpyxl
dich_excel?

2024-01-18 15:38 UTC, didoogan commented on api/management/commands/import_task_from_excel.py
> +    file = "/home/yurii/PROJECTS/kan/api/management/commands/task_importer/task_updates_checked.xlsx"
знову /home/yurii

2024-01-18 15:38 UTC, didoogan commented on api/management/commands/task_importer/task_importer.py
> +                    print(f"{self.counter=}")
я це написав, але треба перенести вище цикла

2024-01-18 15:38 UTC, didoogan commented on api/management/commands/task_importer/task_importer.py
> +    def _create_tasks_from_list(self):
цей метод вже можна видалити

2024-01-18 15:38 UTC, didoogan commented on api/serializers.py
> +        queryset=User.objects.all(), allow_null=True, default=None, many=False, label="Відповідальний"
це можна прибрати, воно вже є в девелопі

2024-01-18 15:39 UTC, didoogan commented
Вище видно, що є конфлікт - його треба зарезолвити

2024-01-19 10:13 UTC, tuipik approved these changes

2024-01-19 14:40 UTC, didoogan approved these changes

2024-01-20 10:16 UTC, merged